package com.test.androidtest20202.constant;

public enum DashboardType {
    VIDEOVIEWPAGER,ANIMATEDBOTTOMBAR,TRANSLATOR,SMARTREPLY,IMAGETEXTRECOGINITION,FACEDETECTION,CHART,AUDIOVISUALIZER,HORIZONTAL_PROGRESS
}
